package com.jegner.dnd.model.modify;

public enum ModifyField {
	HP, CHARACTER_AC, ARMOR_AC, ABILITY_SCORE, INITIATIVE, STRENGTH_MOD, DEXTERITY_MOD, CONSTITUTION_MOD, INTELLIGENCE_MOD, WISDOM_MOD, CHARISMA_MOD
}
